# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Dr. Prashaant Kumar"
email: "your.email@domain.com"
description: >- 
  PhD in AI & Climate Science · Incoming Postdoc at KIT · Working on Geospatial Machine Learning, Satellites, and Low-Level Clouds

url: "https://prashaant-k.github.io" # No trailing slash
baseurl: "" # Leave empty for GitHub Pages

twitter_username: prashaant_k
github_username: prashaant-k
orcid: 0000-0000-0000-0000 # Replace with your actual ORCID
google_scholar: https://scholar.google.com/citations?user=xxxxxx # Replace this

# Author settings
author:
  name   : "Prashaant Kumar"
  avatar : "/assets/images/avatar.jpg" # Upload this image
  bio    : "Postdoctoral Researcher | AI for Climate | Low-Level Cloud Systems"
  location: "Germany"
  links:
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:your.email@domain.com"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/prashaant-k"
    - label: "Google Scholar"
      icon: "ai ai-google-scholar"
      url: "https://scholar.google.com/citations?user=xxxxxx"
    - label: "ORCID"
      icon: "ai ai-orcid"
      url: "https://orcid.org/0000-0000-0000-0000"
    - label: "Twitter"
      icon: "fab fa-twitter"
      url: "https://twitter.com/prashaant_k"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://linkedin.com/in/prashaant-k"

# Theme settings
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: default # Try "air", "dark", "neon" too

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache

markdown: kramdown
highlighter: rouge

paginate: 5
paginate_path: /page:num/

# Analytics (optional)
# google_analytics: UA-XXXXXXXXX-X

# Social sharing
twitter:
  username: prashaant_k

# Include/exclude
include:
  - _pages
  - _posts
  - _data
  - assets
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Defaults for front matter (optional customization later)
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
  - scope:
      path: ""
      type: "pages"
    values:
      layout: single
      author_profile: true
